AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - lib/tasks/cucumber.rake
    - config/environments/*.rb
Documentation:
  Enabled: false
LineLength:
  Max: 160
Style/RaiseArgs:
  EnforcedStyle: compact
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/ClassLength:
  Max: 200
