version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rails
    environment:
      RAILS_ENV: development
      #RAILS_ENV: production
      VIRTUAL_HOST: www.oceano.test
      VIRTUAL_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
