---

- name: install security-related packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - rkhunter
    - lynis
    - ufw

- name: disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: PasswordAuthentication
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: disallow root logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: remove password requirement for sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    state: present

- name: open ssh port
  ufw:
    rule: allow
    port: ssh

- name: default to deny policy
  ufw:
    state: enabled
    policy: deny
