---

- name: create deploy user
  user: 
    name: deploy 
    state: present 
    shell: /bin/bash 
    groups: sudo,www-data

- name: add keys to authorized_keys
  authorized_key: 
    user: deploy
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - keys/*.pub
