weather:
    latitude: 35.7806
    longitude: -78.6389
areas:
    - Corona del Sol
    - Costa Diamente
    - Las Conchas
    - Las Palmas
    - Mirador
    - Playa Encanto
    - Sandy Beach
cache_population_searches:
    - address:
        country: 'MX'
