---

- name: install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libsqlite3-dev
    - nodejs
  tags:
    - oceano

- name: ensure application directory is created
  file:
    path: /var/www
    owner: deploy
    group: deploy
    mode: 0755
    state: directory
  tags:
    - oceano

- name: Set ESCAPIA_USERNAME
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^ESCAPIA_USER'
    line: 'ESCAPIA_USERNAME={{ escapia_username }}'

- name: Set ESCAPIA_PASSWORD
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^ESCAPIA_PASSWORD'
    line: 'ESCAPIA_PASSWORD={{ escapia_password }}'

- name: Set RACK_ENV
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^RACK_ENV'
    line: 'RACK_ENV={{ rack_env }}'

- name: Set RAILS_ENV
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^RAILS_ENV'
    line: 'RAILS_ENV={{ rack_env }}'

- name: Set REDIS_HOST
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^REDIS_HOST'
    line: 'REDIS_HOST={{ redis_host }}'

- name: Set REDIS_PORT
  lineinfile: 
    dest: /etc/environment 
    state: present
    regexp: '^REDIS_PORT'
    line: 'REDIS_PORT={{ redis_port }}'
